POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VscjEwNzYiLCJpZCI6IjYxMWY4ZjNjM2JjOWE1Mjc0MGNjMWFmOSIsImlhdCI6MTYyOTc5OTY4NiwiZXhwIjoxNjI5ODAzMjg2fQ.pN0BTtfQprhn2SFisF9xJ9y_lLWzMonXTGx-4zqiafA

{
    "likes": 4,
    "title": "JavaScript is an asynchronous programming language",
    "author": "Angel Rodriguez",
    "url": "http://www.angelrod.dev"
}