POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VscjEwNzYiLCJpZCI6IjYxMWY4ZjNjM2JjOWE1Mjc0MGNjMWFmOSIsImlhdCI6MTYyOTc3MDAwMiwiZXhwIjoxNjI5NzczNjAyfQ.67ZxBH0WTRDMAEiZuSh0sAHNjsgAQyvCvFTVbq0KVjU

{
    "likes": 4,
    "title": "Testing exercise 4.20",
    "author": "Angel Rodriguez",
    "url": "http://www.angelrod.dev"
}