DELETE http://localhost:3001/api/blogs/61228a6272ac6fc638a8f096
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VscjEwNzYiLCJpZCI6IjYxMWY4ZjNjM2JjOWE1Mjc0MGNjMWFmOSIsImlhdCI6MTYyOTc2ODY3NSwiZXhwIjoxNjI5NzcyMjc1fQ.Iu5bYh9_wrHYdZ4WhivG95Qt00S_Nm5fbjjX53RQK7Y

