POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VscjEwNzYiLCJpZCI6IjYxMWY4ZjNjM2JjOWE1Mjc0MGNjMWFmOSIsImlhdCI6MTYyOTkzODA4NiwiZXhwIjoxNjI5OTQxNjg2fQ.WFajU92hCBx84n787mak7a4LQU2IrIYxmpfTfQXv0tM

{
    "likes": 4,
    "title": "C is a functional programming language",
    "author": "Angel Rodriguez",
    "url": "http://www.angelrod.dev"
}