DELETE http://localhost:3003/api/blogs/6138eab11845864100fea557
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VscjEwNzYiLCJpZCI6IjYxMWY4ZjNjM2JjOWE1Mjc0MGNjMWFmOSIsImlhdCI6MTYzMTEyMDM5OCwiZXhwIjoxNjMxMTIzOTk4fQ.fBJMB-aisvcQJjGvWVa2k2NTfz57Z9rpMtpDmlcTbHg

