POST http://localhost:3003/api/login
Content-Type: application/json

# {
#     "username": "angelr1076",
#     "password": "salainen"
# }
# {
#     "username": "winter",
#     "password": "salainen"
# }
{
    "username": "daisybrat",
    "password": "salainen"
}